module ZenMainLogic(
	output wire LOCK,
	input wire RST,
	input  wire [31:23] A,
	input wire CLK,
	input wire TS_N,
	input wire RW_IN,
	input wire SIZ0,
	input wire SIZ1,
	output wire RW_OUT /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire TA_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire CLA_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire RAM_CS_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire RAM_OE_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire ROM_CS_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire ROM_OE_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */,
	output wire ROM_BUFFER_OE_N /* synthesis DOUT="TRUE" SLEWRATE="FAST" */
	
);
	assign RW_OUT = RW_IN;
	
	wire INT_RAM_CS_N;
	wire INT_RAM_LINE_CS_N;
	
	/******************************** Get clock signals **********************************/
	wire CLKOP;
	wire EARLY_CLK;
	wire CLKOS;
	wire CLKOS2;

	ZenPLL u_ZenPLL(
		.CLKI(CLK), 
		.RST(RST),
		.CLKOP(CLKOP),
		.CLKOS(CLKOS),
		.CLKOS2(CLKOS2),
		.CLKOS3(EARLY_CLK),
		.LOCK(LOCK)
	);

	
	
	/******************************** Memory decoding **********************************/
	
		
	wire RAM_CS_ADDR;
	wire ROM_CS_ADDR;
	wire RAM_TA_N;
	wire RAM_LINE_TA_N;
	wire ROM_TA_N;
	wire LINE;
	
	assign TA_N = RAM_LINE_TA_N&ROM_TA_N&RAM_TA_N;
	assign RAM_CS_N = INT_RAM_LINE_CS_N&INT_RAM_CS_N;	// RAM CS is generated by both LINE and not LINE

	assign LINE = SIZ0&SIZ1;	// True if it's a line burst read or write
	
    ZenAddressDecode u_decode(
		.A(A),
		.RAM_ADDR(RAM_CS_ADDR),
		.ROM_ADDR(ROM_CS_ADDR)
	);
	
	

	
	/******************************** Generate RAM CS and RAM TA **********************************/
	assign RAM_OE_N = RAM_CS_N|!RW_IN;	// Don't assert RAM OE on if it's a write
	
	ZenRAM_CS_TA u_RAM_CS_TA(
		.CLK(EARLY_CLK),
		.CLKOS(CLKOS),
		.ENABLE(RAM_CS_ADDR&!LINE),
		.TS_N(TS_N),
		.RW(RW_IN),
		.RAM_CS_N(INT_RAM_CS_N),
		.RAM_TA_N(RAM_TA_N)
	);
	/******************************** Generate RAM LINE CS and RAM LINE TA **********************************/
	assign RAM_OE_N = RAM_CS_N|!RW_IN;	// Don't assert RAM OE on if it's a write
	
	ZenRAM_Line_CS_TA u_RAM_Line_CS_TA(
		.CLK(CLK),
		.CLKOS(CLKOS),
		.ENABLE(RAM_CS_ADDR&LINE),
		.TS_N(TS_N),
		.RW(RW_IN),
		.CLA_N(CLA_N),
		.RAM_LINE_CS_N(INT_RAM_LINE_CS_N),
		.RAM_LINE_TA_N(RAM_LINE_TA_N)
	);
	
	/************************************* Generate ROM CS and TA ******************************/
	assign ROM_OE_N = ROM_CS_N|!RW_IN;	// Don't assert ROM_OE if it's a write
	assign ROM_BUFFER_OE_N = ROM_CS_N;
	
	ZenROM_CS_TA u_ROM_CS_TA(
		.CLK(CLK),
		.CLKOS(CLKOS2),
		.ENABLE(ROM_CS_ADDR),
		.TS_N(TS_N),
		.RW(RW_IN),
		.ROM_CS_N(ROM_CS_N),
		.ROM_TA_N(ROM_TA_N)
	);
	
endmodule