/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sun Aug 30 13:20:27 2026 */

/* parameterized module instance */
ZenPLL __ (.CLKI( ), .PHASESEL( ), .PHASEDIR( ), .PHASESTEP( ), .RST( ), 
    .CLKOP( ), .CLKOS( ), .CLKOS2( ), .LOCK( ), .DPHSRC( ));
