/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Tue Sep 08 22:09:59 2026 */

/* parameterized module instance */
ZenPLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
