/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.14.0.75.2 */
/* Module Version: 5.7 */
/* Sat Sep 26 17:42:23 2026 */

/* parameterized module instance */
ZenPLL __ (.CLKI( ), .RST( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .LOCK( ));
